#!/usr/bin/python
"""

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.


"""
import sys

def main ():
  
  maxN = 500000
  tri = [n*(n+1)/2 for n in range(1,maxN)]
  pent = [n*(3*n-1)/2 for n in range(1,maxN)]
  hexa = [n*(2*n-1) for n in range(1,maxN)]
  
  #print set(tri).intersection(set(pent))


  print set(tri).intersection(set(pent)).intersection(set(hexa))
  #print pent
  #print hexa
  
  pass

if __name__ == '__main__':

  main()
